source 'http://rubygems.org'

gem 'bundle'
gem 'sinatra', :git => 'git://github.com/sinatra/sinatra.git'
gem 'sequel'
gem 'slim', :git => 'git://github.com/slim-template/slim slim'
gem 'rack', '1.3.3'
gem 'thor', :git => 'git://github.com/wycats/thor.git'
gem 'redcarpet', :git => 'git://github.com/vmg/redcarpet.git'

gem 'pg'
gem 'thin'

gem 'rake'

group :development do
	gem 'sqlite3'
	gem 'mysql'
end

