source 'http://rubygems.org'

gem 'seimtra', '0.0.1'
gem 'sinatra'
gem 'sequel'
gem 'slim'
gem 'rack', '1.3.3'
gem 'thor', :git => 'git://github.com/wycats/thor.git'
gem 'redcarpet', :git => 'git://github.com/vmg/redcarpet.git'

gem 'pg'
gem 'thin'

gem 'rake'
gem 'redcarpet'

group :development do
	gem 'sqlite3'
	gem 'mysql'
end

