source 'http://rubygems.org'

gem 'sequel'
gem 'thor', :git => 'git://github.com/wycats/thor.git'

gem 'sinatra', '1.4.2', :git => 'git://github.com/sinatra/sinatra.git'
gem 'rack', '1.5.2'
gem 'rack-protection', '1.5.0'

gem 'slim', :git => 'git://github.com/slim-template/slim.git', :tag => 'v1.3.8'
gem 'sass'
gem 'tilt'
gem 'temple'

gem 'redcarpet'

gem 'pg'
gem 'thin'

gem 'rake'

group :development do
	gem 'sqlite3'
	gem 'mysql'
end

